'use strict';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='privacidad-unsa-v1';
let saved={};let storageAvailable=true;
try{saved=JSON.parse(localStorage.getItem(KEY)||'{}');if(!saved||typeof saved!=='object'||Array.isArray(saved))saved={};}catch{saved={};storageAvailable=false;}
let page='inicio',query='',role='all',study='all',quizIndex=0,answers={};
const names={'1':'Responsable','2':'Encargado','3':'Seguridad común'};
const states={'':'Sin evaluar','conforme':'Conforme en la muestra','parcial':'Implementación parcial','no':'No conforme','sin':'Evidencia insuficiente','na':'No aplicable · justificado'};
function get(id){const v=saved[id];return v&&typeof v==='object'&&!Array.isArray(v)?v:{};}
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4200);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(saved));storageAvailable=true;}catch{storageAvailable=false;toast('No se pudo guardar en este navegador. Exporta tu matriz para conservarla.');}progress();}
function progress(){const n=CONTROLS.filter(c=>get(c.id).done===true).length;$('#progress-count').textContent=n+' / 78';$('#progress').value=n;}
function header(k,title,desc){return '<div class="page-heading"><div><div class="eyebrow">'+k+'</div><h1>'+title+'</h1><p>'+desc+'</p></div></div>';}
function intro(){return header('TU ESPACIO DE APRENDIZAJE','La privacidad, llevada a la práctica.','Estudia la norma, llévala al contexto universitario y aprende a buscar evidencia.')+
'<section class="hero"><div class="hero-copy"><div class="eyebrow">ISO/IEC 27701:2025 · ANEXOS A, B Y C</div><h1>De entender un control<br>a saber <em>cómo auditarlo.</em></h1><p>Una ruta de estudio con ejemplos para la Universidad Nacional de San Agustín de Arequipa.</p><a class="btn" href="#anexo-a">Explorar los controles <span>↗</span></a></div><div class="hero-art" aria-hidden="true"><div class="orbit"></div><div class="orbit two"></div><div class="orbit three"></div><div class="shield">✓</div><div class="art-label one"><strong>A</strong> Qué proteger</div><div class="art-label two"><strong>B</strong> Cómo hacerlo</div><div class="art-label three"><strong>C</strong> Por qué importa</div></div></section>'+
'<div class="stats"><div class="stat"><strong>03</strong><span>Anexos para profundizar</span></div><div class="stat"><strong>78</strong><span>Controles con casos prácticos</span></div><div class="stat"><strong>11</strong><span>Principios de privacidad</span></div><div class="stat"><strong>01</strong><span>Contexto: la UNSA</span></div></div>'+
'<div class="section-head"><h2>Empieza por el mapa de la norma</h2><span>Un requisito → una acción → una evidencia</span></div><div class="grid3">'+
[['A','NORMATIVO','Los controles','Qué debes considerar para proteger datos: 31 controles del responsable, 18 del encargado y 29 de seguridad común.','anexo-a','Estudiar anexo A'],['B','NORMATIVO','La implementación','Orientaciones correspondientes a cada control de A. Convierte cada objetivo en tareas, responsables y evidencias.','anexo-b','Explorar anexo B'],['C','INFORMATIVO','Los principios','Relaciona los controles con los once principios de ISO/IEC 29100. Comprende la razón de cada protección.','anexo-c','Conectar con los principios']].map(a=>'<article class="card"><span class="letter">'+a[0]+'</span><span class="meta">'+a[1]+'</span><h3>'+a[2]+'</h3><p>'+a[3]+'</p><a href="#'+a[4]+'">'+a[5]+' ↗</a></article>').join('')+'</div>'+
'<div class="info"><strong>Tres anexos prioritarios, seis anexos en total.</strong><p>A.1, A.2 y A.3 son tablas dentro del anexo A. Los anexos D, E y F contienen correspondencias con otros marcos y la edición anterior. Esta guía usa la edición 2025.</p></div>'+
'<div class="split"><section class="card"><h3>Una manera útil de estudiar</h3>'+[['01','Comprende el propósito','Lee qué protege el control y el rol al que corresponde.'],['02','Aplícalo a un proceso','Piensa en matrícula, bienestar, investigación o un convenio.'],['03','Pide evidencia','Comprueba documentos, entrevistas y funcionamiento real.']].map(x=>'<div class="list-row"><span class="step">'+x[0]+'</span><div><b>'+x[1]+'</b><p>'+x[2]+'</p></div></div>').join('')+'</section><section class="card"><span class="pill">DEL CONOCIMIENTO A LA EVIDENCIA</span><h3>Practica tu mirada de auditor</h3><p>Aprende a justificar la aplicabilidad, valorar evidencia y formular un hallazgo. Usa una escala interna sin confundirla con una certificación.</p><a href="#auditoria">Abrir el taller de auditoría ↗</a></section></div>';}
function catalog(isB){return header(isB?'ANEXO B · NORMATIVO':'ANEXO A · NORMATIVO',isB?'Del control a la implementación.':'Un control. Una protección concreta.',isB?'Cada ficha enlaza la referencia B con su control A y desarrolla una aplicación propuesta para la UNSA.':'Explora los 78 controles: entiende el propósito, revisa un ejemplo universitario y prepara la comprobación.')+
'<div class="info">'+(isB?'<strong>A indica el control; B orienta cómo llevarlo a la práctica.</strong><p>B está identificado como normativo en la edición 2025, pero su texto incluye recomendaciones de implementación («should»). No todas las medidas ilustrativas son mandatos universales. Evalúa el requisito de A, las obligaciones aplicables y la eficacia de la solución elegida.</p>':'<strong>La aplicabilidad depende del tratamiento.</strong><p>A.1: responsable que decide finalidades y medios. A.2: encargado que actúa por cuenta de otro. A.3: seguridad para ambos. Justifica inclusiones y exclusiones en la declaración de aplicabilidad; no basta con seleccionar «N/A».</p>')+'</div><div class="toolbar"><input id="search" type="search" aria-label="Buscar controles" placeholder="Buscar por código, tema o ejemplo…"><select id="role" aria-label="Filtrar por rol"><option value="all">Todos los roles · 78</option value="1">A.1 · Responsable · 31</option value="2">A.2 · Encargado · 18</option value="3">A.3 · Seguridad común · 29</option></select><select id="study" aria-label="Filtrar por progreso"><option value="all">Todo el recorrido</option><option value="pending">Por estudiar</option><option value="done">Ya estudiados</option></select></div><div id="result-count" class="count-line" role="status"></div><div class="controls" id="controls"></div>';}
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function cards(){const list=CONTROLS.filter(c=>(role==='all'||c.group===role)&&(study==='all'||(study==='done')===(get(c.id).done===true))&&normalize(Object.values(c).join(' ')).includes(normalize(query)));$('#result-count').textContent=list.length+' controles encontrados · abre una ficha para estudiar y evaluar';$('#controls').innerHTML=list.length?list.map(c=>'<button class="control-card" data-control="'+c.id+'"><span class="ref">'+(page==='anexo-b'?c.b:c.id)+'</span>'+(get(c.id).done?'<span class="done">✓ Estudiado</span>':'')+'<h3>'+c.title+'</h3><p>'+(page==='anexo-b'?c.implement:c.meaning)+'</p><div class="bottom"><span>'+names[c.group]+'</span><span>Ver ficha ↗</span></div></button>').join(''):'<p class="empty">No hay controles con estos filtros. Prueba otro término o selecciona todos los roles.</p>';}
function refs(list){return list?list.split(' ').map(id=>'<button class="ref-btn" data-control="A.'+id+'">A.'+id+'</button>').join(''):'<span class="tag">Sin correspondencia en C.2</span>';}
function annexC(){return header('ANEXO C · INFORMATIVO','La razón detrás del control.','Once principios de ISO/IEC 29100 y su relación indicativa con controles del responsable y del encargado.')+
'<div class="info"><strong>Un mapa, no una certificación adicional.</strong><p>C.1 corresponde a responsables; C.2, a encargados. «Sin correspondencia» no equivale a exención de obligaciones. Este mapa de estudio se reconstruyó del OCR aportado; coteja la tabla original antes de usarla como evidencia formal.</p></div><div class="principles">'+PRINCIPLES.map((p,i)=>'<article class="card principle"><span class="step">'+String(i+1).padStart(2,'0')+'</span><div><h3>'+p[0]+'</h3><p>'+p[1]+'</p><p><strong>Ejemplo UNSA:</strong> '+p[2]+'</p><h4 class="subheading">C.1 · Responsable</h4><div class="references">'+refs(p[3])+'</div><h4 class="subheading">C.2 · Encargado</h4><div class="references">'+refs(p[4])+'</div></div></article>').join('')+'</div><div class="info">Los controles A.3 complementan la seguridad del tratamiento. No se han añadido al mapeo C.1/C.2 como si fueran correspondencias literales de las tablas.</div>';}
function unsa(){return header('APLICACIÓN PROPUESTA · UNSA','Una universidad. Muchos tratamientos.','Empieza por identificar procesos y roles. La misma institución puede ser responsable en un proceso y encargada en otro.')+
'<div class="info note"><strong>Escenarios didácticos, no diagnóstico institucional.</strong><p>No se han revisado sistemas, contratos ni evidencias internas de la UNSA. Las áreas y funciones propuestas deben validarse con su organización vigente.</p></div>'+
'<div class="table-wrap"><table><thead><tr><th>Proceso propuesto</th><th>Datos / riesgo para las personas</th><th>Acción inicial</th><th>Controles para empezar</th></tr></thead><tbody>'+
[['Admisión y matrícula','Identidad, contacto, resultados. Exposición o errores que afecten trámites.','Inventariar finalidades y bases aplicables; minimizar campos; revisar avisos.','1.2.2 1.2.3 1.3.4 1.4.2'],['Bienestar y salud','Datos de salud y situación socioeconómica. Discriminación o divulgación sensible.','Separar accesos, clasificar información y evaluar riesgos e impacto.','1.2.6 3.5 3.9 3.26'],['Investigación','Encuestas, participantes, registros identificables. Reidentificación.','Determinar roles, base aplicable, minimización y cierre del estudio.','1.2.8 1.4.5 1.4.6 3.31'],['Recursos humanos','Legajos, pagos, evaluaciones. Acceso excesivo o cuentas activas tras el cese.','Definir conservación y enlazar cambios de puesto con accesos.','1.4.8 3.8 3.9'],['Plataformas educativas','Cuentas, actividad y calificaciones. Uso secundario o transferencias no previstas.','Revisar contratos, subencargados, destinos y registros de acceso.','1.2.7 1.5.3 3.25'],['Convenio de procesamiento','Datos de otra entidad tratados siguiendo instrucciones. Uso fuera del encargo.','Validar rol de encargado y documentar instrucciones y plan de salida.','2.2.2 2.2.3 2.4.3'],['Videovigilancia propuesta','Imágenes y movimientos. Seguimiento o exposición innecesaria.','Justificar finalidad y necesidad; revisar avisos, accesos y conservación.','1.2.6 1.3.4 1.4.8 3.9']].map(r=>'<tr><td>'+r[0]+'</td><td>'+r[1]+'</td><td>'+r[2]+'</td><td><div class="references">'+refs(r[3])+'</div></td></tr>').join('')+'</tbody></table></div>'+
'<div class="section-head"><h2>Ruta sugerida de implementación</h2><span>Horizonte ilustrativo · ajustar al alcance y recursos</span></div><div class="roadmap">'+
[['01 · Semanas 1–2','Definir alcance y gobierno','Dirección, responsables de procesos y función de privacidad: delimitar unidades, sistemas y roles. Identificar partes interesadas y obligaciones.','Alcance del SGIP, responsables, política y mapa inicial. Cláusulas 4 y 5.'],
['02 · Semanas 3–4','Inventariar y evaluar riesgos','Responsables de procesos, TI y asesoría jurídica: registrar flujos, datos, finalidades y bases; evaluar consecuencias para las personas.','Inventario, matriz legal y riesgos; evaluación de impacto cuando corresponda. Cláusula 6.'],
['03 · Semanas 5–6','Decidir controles y aplicabilidad','Equipo del SGIP: seleccionar controles necesarios, justificar exclusiones, asignar recursos, fechas y dueños.','Declaración de aplicabilidad y plan de tratamiento aprobados. Cláusulas 6 y 7.'],
['04 · Semanas 7–10','Implementar y dejar evidencia','Dueños de proceso y TI: poner en marcha derechos, contratos, permisos, retención y respuesta a incidentes; capacitar.','Procedimientos operativos, registros y pruebas de funcionamiento. Cláusulas 7 y 8.'],
['05 · Semanas 11–12','Auditar y mejorar','Auditoría independiente y dirección: comprobar eficacia, revisar resultados, corregir causas y verificar acciones.','Informe de auditoría, revisión por dirección y acciones correctivas verificadas. Cláusulas 9 y 10.']].map(r=>'<article class="card"><span class="pill">'+r[0]+'</span><h3>'+r[1]+'</h3><p>'+r[2]+'</p><p><strong>Salida verificable:</strong> '+r[3]+'</p></article>').join('')+'</div><div class="info"><strong>El sistema de gestión también cuenta.</strong><p>Estudiar los anexos no sustituye las cláusulas 4–10: contexto, liderazgo, planificación, soporte, operación, evaluación del desempeño y mejora.</p></div>';}
function audit(){const vals=CONTROLS.map(c=>get(c.id));const evaluated=vals.filter(v=>v.status&&v.status!=='na').length;const conform=vals.filter(v=>v.status==='conforme').length;const na=vals.filter(v=>v.status==='na').length;return header('TALLER DE AUDITORÍA','No basta con que exista una política.','Comprueba el diseño del control, su aplicación y su eficacia. Evalúa siempre contra un criterio identificado.')+
'<div class="info note"><strong>Estas escalas son propuestas de aprendizaje, no umbrales ISO.</strong><p>La norma no fija porcentajes de certificación, tamaños universales de muestra ni plazos internos únicos. La conformidad se determina por requisito y evidencia. No compenses una desviación grave con un promedio alto.</p></div>'+
'<div class="flow">'+[['01','Fija el criterio','Control aplicable, obligación legal, contrato y procedimiento aprobado.'],['02','Define la muestra','Periodo, población, selección y riesgo. Incluye casos normales y excepciones.'],['03','Triangula evidencia','Documento + entrevista + observación o prueba autorizada.'],['04','Sustenta la conclusión','Compara condición observada con criterio y registra límites del muestreo.']].map(r=>'<article class="card"><b>'+r[0]+'</b><h3>'+r[1]+'</h3><p>'+r[2]+'</p></article>').join('')+'</div>'+
'<h2>¿En qué rangos basarte?</h2><p>Separa tres decisiones: el estado del control, su madurez y el nivel de riesgo para las personas.</p>'+
'<div class="table-wrap"><table><thead><tr><th>Estado</th><th>Criterio de consideración propuesto</th><th>Qué hacer</th></tr></thead><tbody>'+
[['Conforme en la muestra','La evidencia suficiente demuestra el cumplimiento del criterio revisado.','Registrar alcance y muestra; no generalizar más allá de la evidencia.'],['Implementación parcial','Existe diseño o aplicación incompleta. Es una etiqueta de avance, no una conformidad parcial oficial.','Identificar requisitos incumplidos y formular hallazgos cuando corresponda.'],['No conforme','Hay evidencia objetiva de incumplimiento de un requisito aplicable.','Citar criterio, condición y evidencia; determinar acción correctiva.'],['Evidencia insuficiente','No hay evidencia suficiente para concluir. No equivale a demostrar cumplimiento.','Ampliar pruebas; si un registro exigido falta, evaluar la no conformidad correspondiente.'],['No aplicable','Exclusión justificada por alcance, rol, riesgo y obligaciones.','Registrar y revisar la justificación en la declaración de aplicabilidad.']].map(r=>'<tr>'+r.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'+
'<div class="section-head"><h2>Madurez interna · escala propuesta de 0 a 4</h2></div><div class="table-wrap"><table><thead><tr><th>Nivel</th><th>Evidencia esperada</th></tr></thead><tbody>'+[['0 · Ausente','Sin mecanismo establecido ni evidencia de operación.'],['1 · Inicial','Actuaciones aisladas, dependientes de personas y sin consistencia.'],['2 · Definido','Procedimiento, responsable y registros previstos; despliegue todavía incompleto.'],['3 · Operativo','Aplicación consistente y evidencia de eficacia en la muestra examinada.'],['4 · Mejorado','Medición sostenida, revisiones y mejoras cuya eficacia se ha verificado.']].map(r=>'<tr><td>'+r[0]+'</td><td>'+r[1]+'</td></tr>').join('')+'</tbody></table></div>'+
'<div class="split" style="margin-top:22px"><section class="card"><h3>Prioriza el riesgo para las personas</h3><p>Modelo didáctico: probabilidad × impacto. Estima el riesgo inherente y vuelve a evaluar el residual después de los controles.</p><div class="risk-inputs"><label>Probabilidad<select class="form-control" id="probability">'+['1 · Excepcional','2 · Poco probable','3 · Posible','4 · Probable','5 · Muy probable'].map((x,i)=>'<option value="'+(i+1)+'">'+x+'</option>').join('')+'</select></label><label>Impacto sobre las personas<select class="form-control" id="impact">'+['1 · Molestia menor','2 · Perjuicio limitado','3 · Perjuicio significativo','4 · Daño grave','5 · Daño muy grave o duradero'].map((x,i)=>'<option value="'+(i+1)+'">'+x+'</option>').join('')+'</select></label></div><div id="risk-result" class="risk-output" role="status"></div><p><small>Rangos propuestos: 1–4 bajo, 5–9 moderado, 10–16 alto, 17–25 crítico. La dirección debe aprobar y contextualizar criterios; aceptar un riesgo no permite incumplir una obligación.</small></p></section><section class="card"><h3>Cómo diseñar una muestra</h3><p>Define población, periodo y método antes de probar. Combina casos por riesgo con una selección que reduzca sesgos.</p><p><strong>Ejemplo didáctico:</strong> examinar todas las cuentas privilegiadas y una muestra de altas, cambios y bajas de un semestre. Registrar cuántas existen, cuántas se revisaron y cómo se eligieron.</p><p>Amplía la muestra ante desviaciones. Una selección por juicio no permite afirmar confianza estadística. No existe una regla ISO de «revisar siempre diez casos».</p></section></div>'+
'<div class="section-head"><h2>Ejemplo de hallazgo</h2></div><section class="card"><p><strong>Criterio:</strong> A.3.9 y política interna aprobada de retiro de accesos.</p><p><strong>Condición ficticia:</strong> en 3 de 12 bajas revisadas, el permiso seguía activo después del plazo definido por la institución. Una prueba autorizada confirmó acceso a expedientes.</p><p><strong>Evidencia:</strong> identificadores seudonimizados de casos, fechas de cese, exportación controlada de permisos y acta de prueba.</p><p><strong>Conclusión:</strong> incumplimiento del criterio citado. Analizar extensión y carácter sistémico para clasificarlo según las reglas del programa de auditoría.</p><p><strong>Corrección y seguimiento:</strong> retirar accesos indebidos, investigar la causa, corregir el flujo de bajas y volver a probar su eficacia.</p></section>'+
'<div class="info"><strong>Mayor, menor u oportunidad de mejora.</strong><p>Como orientación, una falla sistémica o que compromete la capacidad del sistema para lograr sus resultados puede justificar una no conformidad mayor; una desviación limitada puede ser menor. Aplica las definiciones del programa o esquema de auditoría. Una oportunidad de mejora no debe ocultar un incumplimiento. La severidad del hallazgo no se calcula automáticamente con el puntaje de riesgo.</p></div>'+
'<div class="section-head"><h2>Tu matriz de práctica</h2><span>Completa las evaluaciones dentro de las fichas</span></div><div class="assessment-grid"><div class="card"><span class="summary-num">'+evaluated+'</span><p>Controles con estado de evaluación</p></div><div class="card"><span class="summary-num">'+conform+'</span><p>Conformes en la muestra declarada</p></div><div class="card"><span class="summary-num">'+na+'</span><p>Exclusiones justificadas registradas</p></div></div><div class="toolbar"><a class="btn" href="#anexo-a">Evaluar controles ↗</a><button class="btn secondary" id="export">Exportar matriz CSV ↓</button><button class="btn secondary" id="backup">Guardar respaldo JSON ↓</button><label class="btn secondary">Restaurar respaldo <input type="file" id="import" accept=".json,application/json" hidden></label></div><p><small>Datos locales a este navegador. Registra referencias seudonimizadas, no expedientes personales. La exportación incluye todos los controles y su estado; no emite un certificado.</small></p>';}
function risk(){const r=Number($('#probability').value)*Number($('#impact').value);const [label,action]=r<=4?['Bajo','Seguimiento rutinario y decisión de aceptación documentada según criterios aprobados.']:r<=9?['Moderado','Programar tratamiento y seguimiento con un responsable.']:r<=16?['Alto','Priorizar medidas y escalamiento a responsables de decisión.']:['Crítico','Escalar con urgencia y evaluar detener o limitar el tratamiento hasta controlar el riesgo.'];$('#risk-result').innerHTML='<strong>'+r+' / 25 · '+label+'</strong><p>'+action+'</p>';}
function practice(){if(quizIndex>=QUIZ.length){const n=QUIZ.filter((q,i)=>answers[i]===q[2]).length;return header('AUTOEVALUACIÓN','Un paso más en tu aprendizaje.','Este resultado mide tus respuestas al cuestionario, no la conformidad de una institución.')+'<section class="card quiz"><span class="eyebrow">RECORRIDO COMPLETADO</span><h2>'+n+' de '+QUIZ.length+' respuestas correctas</h2><p>Repasa las explicaciones y vuelve a las fichas relacionadas.</p>'+QUIZ.map((q,i)=>'<div class="detail-section"><h3>'+(answers[i]===q[2]?'✓ ':'↻ ')+q[0]+'</h3><p>'+q[3]+'</p></div>').join('')+'<button class="btn" style="margin-top:20px" id="restart">Volver a practicar</button></section>';}
const q=QUIZ[quizIndex],answered=answers[quizIndex]!==undefined;return header('PONLO A PRUEBA','Piensa como quien audita.','Doce situaciones para conectar la norma, la universidad y la evidencia.')+'<section class="card quiz"><div class="quiz-top"><span>Pregunta '+(quizIndex+1)+' de '+QUIZ.length+'</span><span>Práctica con explicación</span></div><h2>'+q[0]+'</h2><div class="quiz-options">'+q[1].map((a,i)=>'<button class="quiz-option '+(answered?(i===q[2]?'correct':i===answers[quizIndex]?'wrong':''):'')+'" data-answer="'+i+'" '+(answered?'disabled':'')+'>'+String.fromCharCode(65+i)+'. '+a+'</button>').join('')+'</div>'+(answered?'<div class="info" role="status"><strong>'+(answers[quizIndex]===q[2]?'Correcto.':'Revisa el criterio.')+'</strong><p>'+q[3]+'</p></div>':'')+'<div class="quiz-actions"><button class="btn secondary" id="prev-question" '+(!quizIndex?'disabled':'')+'>← Anterior</button><button class="btn" id="next-question" '+(!answered?'disabled':'')+'>'+(quizIndex===QUIZ.length-1?'Ver resultado':'Siguiente →')+'</button></div></section>';}
function sources(){return header('FUENTES Y ALCANCE','Estudia con contexto y trazabilidad.','Esta guía es una síntesis educativa original, preparada a partir del documento aportado y referencias oficiales.')+
'<section class="card sources"><h2>Documento de trabajo</h2><p><strong>ISO_IEC_27701_2025.md</strong>, conversión OCR proporcionada en la carpeta del proyecto. Referencias: anexo A, páginas marcadas 21–26; B, 27–56; C, 57–58; D, desde 59; E, desde su encabezado; F, desde su encabezado. Las marcas corresponden al archivo convertido, no necesariamente a la numeración impresa.</p><p>El OCR contiene errores en numeración y tablas. Los identificadores de A se contrastaron con los encabezados correspondientes de B; por ejemplo, A.3.30 y A.3.31 se recuperaron de B. En C aparece A.1.8.2 en el OCR: se interpretó como A.1.5.2 por el título coincidente. Las correspondencias deben cotejarse con una copia autorizada antes de una auditoría formal.</p><p>Las fichas parafrasean objetivos y desarrollan propuestas prácticas; no constituyen traducción oficial ni sustituyen el texto normativo. La publicación del sitio no incluye el documento ISO completo.</p><h2>Referencias oficiales</h2><ul><li><a href="https://www.iso.org/standard/27701" target="_blank" rel="noopener">ISO · ISO/IEC 27701:2025, segunda edición ↗</a>. Fuente para identidad, alcance y carácter independiente del sistema de gestión.</li><li><a href="https://diariooficial.elperuano.pe/Normas/obtenerDocumento?idNorma=23" target="_blank" rel="noopener">El Peruano · Ley 29733 y reglamento de protección de datos personales ↗</a>.</li><li><a href="https://www3.congreso.gob.pe/Docs/DGP/DIDP/files/ds_016-2024-jus.pdf" target="_blank" rel="noopener">Congreso · Decreto Supremo 016-2024-JUS ↗</a>, texto oficial del nuevo reglamento.</li><li><a href="https://www.elperuano.pe/noticia/259141--peru-fortalece-la-proteccion-de-datos-estos-son-los-principales-cambios-del-nuevo-reglamento" target="_blank" rel="noopener">El Peruano · entrada en vigor del reglamento el 31 de marzo de 2025 ↗</a>. Revisar disposiciones específicas y transitorias aplicables.</li><li><a href="https://www.gob.pe/institucion/anpd/colecciones/3482-normativa-de-proteccion-de-datos-" target="_blank" rel="noopener">ANPD · compendio de normativa ↗</a>, para actualizar la matriz legal antes de una implementación real.</li></ul><p><strong>Fecha de preparación:</strong> 5 de octubre de 2026. Las obligaciones, plazos y reglas de aplicación deben verificarse con el texto vigente para el tratamiento concreto; esta guía no asigna una base legal única a toda la universidad.</p></section>'+
'<div class="section-head"><h2>¿Qué contienen los otros anexos?</h2></div><div class="grid3">'+[['D','Correspondencia con RGPD','Mapeo informativo al Reglamento General de Protección de Datos europeo. No implica que sea aplicable automáticamente a la UNSA.'],['E','Otros marcos de privacidad','Mapeo informativo a ISO/IEC 27018 e ISO/IEC 29151; útil para relacionar controles existentes.'],['F','Transición desde 2019','Correspondencia informativa con la edición anterior. Evita confundir la estructura de 2019 con la de 2025.']].map(r=>'<article class="card"><span class="letter">'+r[0]+'</span><h3>'+r[1]+'</h3><p>'+r[2]+'</p></article>').join('')+'</div>'+
'<section class="card sources" style="margin-top:22px"><h2>Vocabulario esencial</h2><p><strong>PII:</strong> información que identifica o puede vincularse a una persona. En esta guía se explica como datos personales, sin sustituir las definiciones legales.</p><p><strong>Titular / PII principal:</strong> persona a la que se refieren los datos. <strong>Responsable:</strong> decide finalidades y medios. <strong>Encargado:</strong> trata por cuenta del responsable.</p><p><strong>SGIP / PIMS:</strong> sistema de gestión de información de privacidad. <strong>Declaración de aplicabilidad:</strong> documento que identifica controles necesarios, justificaciones, estado de implementación y exclusiones justificadas.</p><p><strong>Seudonimización:</strong> sustituir identificadores manteniendo posibilidad de vinculación con información adicional; no equivale a anonimización.</p><h2>Cómo usar tus registros</h2><p>El progreso y las notas se guardan en el almacenamiento local de este navegador. Cambiar de dispositivo o borrar datos del navegador puede perderlos; exporta un respaldo desde el taller. No hay sincronización con la universidad ni envío de notas al servidor. La tipografía puede solicitarse a Google Fonts; el resto funciona con archivos estáticos.</p></section>';}
function showControl(id){const c=CONTROLS.find(c=>c.id===id);if(!c)return;const v=get(id);$('#dialog-body').innerHTML='<div class="eyebrow">'+c.id+' · '+c.b+' · '+names[c.group]+'</div><h2 id="dialog-title">'+c.title+'</h2><span class="pill">Síntesis educativa + aplicación propuesta</span>'+
[['Qué significa',c.meaning],['Cómo lo implementaría en la UNSA',c.implement],['Cómo verificaría su cumplimiento',c.audit],['Criterio de aceptación para la prueba',c.criterion]].map(s=>'<section class="detail-section"><h3>'+s[0]+'</h3><p>'+s[1]+'</p></section>').join('')+
'<div class="info">Guía relacionada: <strong>'+c.b+'</strong>. Define dueño, procedimiento, registros y revisión de eficacia para esta implementación. La evidencia de la muestra debe ser suficiente para el criterio; no se establece un porcentaje automático de aprobación.</div>'+
'<section class="detail-section"><h3>Tu evaluación de práctica</h3><label for="assessment">Estado del control</label><select class="form-control" id="assessment">'+Object.entries(states).map(([key,label])=>'<option value="'+key+'" '+(v.status===key?'selected':'')+'>'+label+'</option>').join('')+'</select><label for="maturity">Madurez interna · escala propuesta</label><select class="form-control" id="maturity"><option value="">Sin valorar</option>'+['Ausente','Inicial','Definido','Operativo','Mejorado'].map((x,i)=>'<option value="'+i+'" '+(String(v.maturity)===String(i)?'selected':'')+'>'+i+' · '+x+'</option>').join('')+'</select><label for="evidence">Criterio, muestra y evidencia / justificación si no aplica</label><textarea id="evidence" maxlength="6000" placeholder="Ej.: política y versión, periodo, población, muestra, prueba y referencia de evidencia. Si no aplica, explica por qué.">'+esc(v.note||'')+'</textarea><label class="checklabel"><input id="studied" type="checkbox" '+(v.done?'checked':'')+'>Ya estudié este control</label></section><div class="dialog-actions"><button class="btn" id="save-control">Guardar evaluación</button><button class="btn secondary" id="close-control">Cerrar</button></div>';
const dialog=$('#control-dialog');if(!dialog.open)dialog.showModal();dialog.scrollTop=0;
$('#save-control').onclick=()=>{const status=$('#assessment').value,note=$('#evidence').value.trim();if(status&&!note){toast('Añade evidencia, límites de la prueba o la justificación de exclusión.');$('#evidence').focus();return;}saved[id]={status,note,maturity:$('#maturity').value,done:$('#studied').checked};persist();dialog.close();if(page==='anexo-a'||page==='anexo-b')cards();if(page==='auditoria')render(false);toast(storageAvailable?'Evaluación guardada en este navegador.':'Evaluación en memoria; exporta un respaldo para conservarla.');};
$('#close-control').onclick=()=>dialog.close();}
function download(content,type,name){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportCsv(){const cell=v=>{let s=String(v??'');if(/^[=+@\-\t\r\n]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const rows=[['Control','Guía','Título','Rol','Estado','Madurez interna 0-4','Estudiado','Evidencia o justificación','Prueba propuesta','Criterio propuesto'],...CONTROLS.map(c=>{const v=get(c.id);return[c.id,c.b,c.title,names[c.group],states[v.status||''],v.maturity??'',v.done?'Sí':'No',v.note||'',c.audit,c.criterion];})];download('\ufeff'+rows.map(r=>r.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8','matriz-estudio-iso27701-unsa.csv');}
async function restore(file){if(!file)return;if(file.size>1500000){toast('Archivo demasiado grande. Usa un respaldo de esta página.');return;}try{const obj=JSON.parse(await file.text());if(obj.version!==1||!obj.controls||typeof obj.controls!=='object'||Array.isArray(obj.controls))throw Error();const out={};for(const c of CONTROLS){if(!Object.hasOwn(obj.controls,c.id))continue;const v=obj.controls[c.id];if(!v||typeof v!=='object'||Array.isArray(v)||!Object.hasOwn(states,v.status??'')||!['','0','1','2','3','4'].includes(v.maturity??'')||typeof v.note!=='string'||v.note.length>6000||typeof v.done!=='boolean'||(v.status&&!v.note.trim()))throw Error();out[c.id]={status:v.status||'',maturity:v.maturity||'',note:v.note,done:v.done};}if(!confirm('¿Reemplazar tus registros locales con este respaldo? Exporta primero si deseas conservar los actuales.'))return;saved=out;persist();render(false);toast('Respaldo restaurado.');}catch{toast('No se pudo importar: el respaldo no tiene el formato esperado.');}}
function render(scroll=true){const valid=['inicio','anexo-a','anexo-b','anexo-c','unsa','auditoria','practica','fuentes'];page=location.hash.slice(1)||'inicio';if(!valid.includes(page))page='inicio';document.querySelectorAll('nav a').forEach(a=>{const active=a.dataset.page===page;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
const views={inicio:intro,'anexo-a':()=>catalog(false),'anexo-b':()=>catalog(true),'anexo-c':annexC,unsa,auditoria:audit,practica:practice,fuentes:sources};$('#main').innerHTML=views[page]();document.title=({'inicio':'Panorama','anexo-a':'Anexo A','anexo-b':'Anexo B','anexo-c':'Anexo C',unsa:'Aplicación UNSA',auditoria:'Auditoría',practica:'Práctica',fuentes:'Fuentes'}[page])+' · Privacidad Aula UNSA';
if(page==='anexo-a'||page==='anexo-b'){$('#search').value=query;$('#role').value=role;$('#study').value=study;$('#search').oninput=e=>{query=e.target.value;cards();};$('#role').onchange=e=>{role=e.target.value;cards();};$('#study').onchange=e=>{study=e.target.value;cards();};cards();}
if(page==='auditoria'){risk();$('#probability').onchange=risk;$('#impact').onchange=risk;$('#export').onclick=exportCsv;$('#backup').onclick=()=>download(JSON.stringify({version:1,exportedAt:new Date().toISOString(),controls:saved},null,2),'application/json','respaldo-privacidad-unsa.json');$('#import').onchange=e=>restore(e.target.files[0]);}
if(page==='practica'){if($('#next-question'))$('#next-question').onclick=()=>{quizIndex++;render(false);};if($('#prev-question'))$('#prev-question').onclick=()=>{quizIndex--;render(false);};if($('#restart'))$('#restart').onclick=()=>{quizIndex=0;answers={};render(false);};}
progress();if(scroll){window.scrollTo(0,0);$('#main').focus({preventScroll:true});}}
document.addEventListener('click',e=>{const control=e.target.closest('[data-control]');if(control)showControl(control.dataset.control);const answer=e.target.closest('[data-answer]');if(answer&&answers[quizIndex]===undefined){answers[quizIndex]=Number(answer.dataset.answer);render(false);}});
$('#control-dialog .close').onclick=()=>$('#control-dialog').close();
window.addEventListener('hashchange',()=>render());
render(false);
